travis:
  secure:
    BINSTAR_TOKEN: V0bMC4Zqa+xee6gSHny6by3XYoSVrX3lu9MaUhBkPEMJ7wAWUiAnuBzE+8NoN1OpNXiOgOhDlGSZZFQxrj0Dqq/gf+WioS16oyf96IEsmEUQkrLgLxyLWKb8hJNU9gvECMC1WpEjvJOpWAudvcqVsP6TkocoXi8QVRTZSxh5IazV1ofXbOaxSoE1ygsoSJvg0DnwxHvUqmwHyB/T5Ax6m2XPQmshU6OJB6cMbDoAb0xQp96TZ6bO6eH4xsDhL9YLrbLgXYNOIhFr+tJCWFxxjx0K8ZYCyf/bJ1dnUdiG5dFVzK2bfHa+uWaKMYHcC2KTSIg5m9Ov8K8phTuRm5xNn2Tvdq948bhKllC0sUExUSMBVccMIyddVC1aP2bDVgqBy5s/cQphfqcPApnIDzNbQTTSzSwCFRigWdXGx5oIF+4FOkI9VSRr4rw4FP9OVRKzOn2rwUVrMyO3Uv/Rp7h0bLgoReV8aWJ/su5sxaE4mypKIKyPz8ji4eEMx9o8IwbrnxZho0Cd6jg54utWjRrfu8hfhnH8jDYS0rSSnLJXBExH717E+X9N8h6kT1fGErMhmsx/nKi6+Bt+PM1wpr7QGfwVo8iyifxJNMqqEFdadv3orJoJXz4G4in+3k6APFII9OF7Q0uwChR3uVMtoKQWAex8GSGj1iPXKYslbx7lZfA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
